apiVersion: apps/v1
kind: Deployment
metadata:
  name: tuni-portfolio
  namespace: tuni-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tuni-portfolio
  template:
    metadata:
      labels:
        app: tuni-portfolio
    spec:
      containers:
        - name: tuni-portfolio
          image: ghcr.io/etunidev/tuni-portfolio:1e45ac004cebbf8509fb380e750a20f3e2b8d75f
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
