apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tuni-portfolio
  namespace: tuni-portfolio
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - tuni.dev
      secretName: tuni-dev-tls
  rules:
    - host: tuni.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tuni-portfolio
                port:
                  number: 80
