apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tuni-portfolio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/etunidev/tuni-portfolio
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: tuni-portfolio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
